### ISSUE TITLE
Possibility to opt-out of steps

### ISSUE THREAD

**Issue by nico-w** [jakeg/heroku-buildpack-bun#10]
Thanks for this great buildpack!

We used your buildpack to simply install bun, install dependencies with bun and then use the node buildpack to run the remaining actions. This is needed, because we're in the middle of a migration phase and not everything is bun compatible yet - and it yet won't be for quite some time I think.

Unfortunately, after your recent changes, we need to use an older version of your buildpack because the latest one is breaking our heroku build process. Get me right, the changes you did were great, but they simply doesn't work (yet) for us!

Would there be any chance that we could add possibility to opt-out of some steps?
Maybe via a config file?

Let me know what you think.

**Comment by jakeg** [comment]
I'm thinking could do this with an optional file. What actions are you hoping to do/skip?

**Comment by nico-w** [comment]
For me, it's basically skipping any action except of installing bun itself and running `bun install`.

So, I'd like to be able to skip:
- `has_heroku_prebuild_script`
- `has_build_script`
- `has_heroku_postbuild_script`

Basically, everything that is here:
https://github.com/jakeg/heroku-buildpack-bun/blob/75d47baa2075efa17f4f48bdc2fd4480b33582dd/bin/compile#L69-L89

But maybe it makes sense to also be able to opt-out of `bun install`.
That would make this buildpack even more flexible for projects that don't use bun yet as a package manger.

**Comment by jakeg** [comment]
This should now be possible with files named `.skip-bun-[xxx]` eg `.skip-bun-heroku-prebuild`. Please do confirm if you have a chance to try it out.

**Comment by nico-w** [comment]
@jakeg Works like a charm! Thanks a ton!! ❤️
