### ISSUE TITLE
Specify bun version with `.bun-version` file (without `v` prefix)

### ISSUE THREAD

**Issue by nico-w** [jakeg/heroku-buildpack-bun#11]
What about adding support for specifying the bun version from yet another, maybe custom file?
I also think it's a good idea to make the version prefix `v` optional.

Take this as an example https://github.com/oven-sh/setup-bun?tab=readme-ov-file#inputs where one can read the content out of the `.bun-version` file to specify the bun version for the GitHub action.

Currently, we have two files in our repository `runtime.bun.txt` and `.bun-version` with the same information (except the `v`). And it would be really cool, if we can rely on just one single file, in our case `.bun-version`.

What do you think?

**Comment by jakeg** [comment]
Seems reasonable. Note you can also set a heroku config variable `BUN_VERSION` but I presume you'd still like this?

**Comment by nico-w** [comment]
Yes, I know that I could set `BUN_VERSION` in heroku ENVs which is actually cool as well but this is yet another place I'd need to check and maintain. So, I'd really prefer to have it set in just one single file.

**Comment by jakeg** [comment]
Should now work with `.bun-version` and the `v` prefix to version numbers is now optional.

**Comment by nico-w** [comment]
@jakeg Works beautifully! thanks!
