### ISSUE TITLE
Enable Bash's `pipefail` mode

### ISSUE THREAD

**Issue by edmorley** [jakeg/heroku-buildpack-bun#13]
The `bin/compile` script currently enables Bash's "exit on error" mode, which is a great start - however, doesn't enable Bash's `pipefail` mode.

Without `pipefail` being enabled, whenever a sequence of commands is run using pipes (eg `command_one | command_two`) Bash only looks at the exit code of the final command, which can mean errors don't result in the script aborting. 

For this buildpack that can result in a broken/incomplete build being deployed to production, given the buildpack uses pipes in several places, eg:
https://github.com/jakeg/heroku-buildpack-bun/blob/cded310383f8809383e2608eafc08e1773cad266/bin/compile#L54
https://github.com/jakeg/heroku-buildpack-bun/blob/cded310383f8809383e2608eafc08e1773cad266/lib/json.sh#L38

See also:
http://redsymbol.net/articles/unofficial-bash-strict-mode/
https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

(This was reported to us in https://heroku.support/1457264)

**Comment by jakeg** [comment]
Thank you for your contribution.

btw when I tried to look at the support ticket you mentioned it wouldn't let me see it, I presume because only Heroku employees can see them?

**Comment by edmorley** [comment]
> btw when I tried to look at the support ticket you mentioned it wouldn't let me see it

Sorry yeah that's expected - I included the support ticket mention part as an example that the issue wasn't just a hypothetical, and part for my own reference so I could find the ticket later :-)

**Comment by edmorley** [comment]
Thank you for adding the `set -o pipefail` :-)
