### ISSUE TITLE
Add support for `BUN_VERSION` env var

### ISSUE THREAD

**Issue by touhidurrr** [jakeg/heroku-buildpack-bun#3]
Heroku already support `NODE_VERSION` env var so it only makes sense to add support for `BUN_VERSION` also.
Render already has this feature. https://docs.render.com/bun-version

**Comment by jakeg** [comment]
> Pin a certain Bun version with a `runtime.bun.txt` or `runtime.txt` with e.g. `v1.0.7` in it.

... are you aware the above is already supported, or do you need the env var anyway?

**Comment by touhidurrr** [comment]
env var is better. `runtime.bun.txt` feels like a nonstandard file.
