### ISSUE TITLE
Build failure on Heroku-24 stack

### ISSUE THREAD

**Issue by touhidurrr** [jakeg/heroku-buildpack-bun#6]
Heroku-24 stack has been made default recently. When I upgraded to it, builds were failing...

![image](https://github.com/jakeg/heroku-buildpack-bun/assets/46617994/54a0a2c0-94f7-4b0a-9e05-19bf9f45a104)

**Comment by jakeg** [comment]
@touhidurrr thanks for reporting this; should now be fixed. Was the `-T` flag to `cp` that was failing.
